apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-aplicacion-deployment
  labels:
    app: mi-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mi-app
  template:
    metadata:
      labels:
        app: mi-app
    spec:
      containers:
      - name: contenedor-nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mi-aplicacion-servicio
spec:
  type: LoadBalancer
  selector:
    app: mi-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80