apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest-deployment
  labels:
    app: speedtest-app
spec:
  replicas: 4 # Tus 4 pods listos para aguantar las pruebas de velocidad
  selector:
    matchLabels:
      app: speedtest-app
  template:
    metadata:
      labels:
        app: speedtest-app
    spec:
      containers:
      - name: speedtest-ctr
        image: openspeedtest/latest:latest
        ports:
        - containerPort: 3000 # El puerto interno en el que viene configurada la app
---
apiVersion: v1
kind: Service
metadata:
  name: speedtest-servicio
spec:
  type: LoadBalancer
  selector:
    app: speedtest-app
  ports:
    - protocol: TCP
      port: 9500      # <--- Usaremos el puerto 9500 para acceder desde fuera
      targetPort: 3000